---
title: "PGMs -- An Odyssey"
subtitle: "Book 3: Variable Elimination"
author: "Ben Teo"
date: "5/9/2022"
output:
  ioslides_presentation:
    self_contained: false
    mathjax: local
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F)
```

$\newcommand{\indep}{\perp\!\!\!\perp}$
$\newcommand{\QED}{\scriptsize{\square}}$
$\DeclareMathOperator{\argmin}{\arg\min}$

## VE Algorithm

<font size="5">

1. Select an $X_i\in\mathcal{X}$ and multiply all $\phi\in\Phi$ that
involve it to produce factor $\psi_i$.
2. Sum out $X_i$ from $\psi_i$ to produce factor $\tau_i$.
    - $\text{Scope}[\tau_i]=\text{Scope}[\psi_i]\setminus\{X_i\}$.
3. Remove $X_i$ from $\mathcal{X}$. Remove all $\phi$ used to produce $\psi_i$
from $\Phi$. Add $\tau_i$ to $\Phi$.
4. Repeat from the start till the desired marginal is attained (i.e. till only
the variables of interest remain in $\mathcal{X}$).

The computational cost of the algorithm is dominated by the sizes (i.e. number
of entries) of the intermediate factors ($\psi_i$s) generated.

</font>

## Complexity: graph representation

<font size="5">

<def>
$\mathcal{H}_{\Phi}$ is an undirected graph whose nodes correspond to the
variables in $\cup_{\phi\in\Phi}\text{Scope}[\phi]$, and whose edges correspond
to pairs of variables that are both found in the scope of some common
$\phi\in\Phi$.
</def>

- By construction, $\mathcal{H}_\Phi$ is a minimal I-map for the distribution
induced by $\Phi$.

<prp>
Let $P_\Phi$ be a Gibbs distribution. Then $\mathcal{H}_\Phi$ is a minimal I-map
for $P_\Phi$ and $P_\Phi$ factorizes over $\mathcal{H}_\Phi$ (i.e. $\Phi$
parameterizes the network).
</prp>

</font>

## Complexity: graph transformation

<font size="5">

Effect of a VE step on the associated Markov network.

1. Producing $\psi$ generates edges among the initial factors $\phi$s that it is
a product of.
2. Summing out $X$ from $\psi$ removes $X$ and all of its incident edges.

Thus the VE steps are mirrored by a sequence of graph transformations, where
each factor is represented as a clique.

<def>
The induced graph $\mathcal{I}_{\Phi,\prec}$ is an undirected graph over
$\mathcal{X}$, where $X_i$ and $X_j$ are connected by an edge if they both
appear in some intermediate factor $\psi$ generated by VE using ordering
$\prec$.
</def>

</font>

## Complexity: graph transformation

<font size="5">

<thm>
Let $\mathcal{I}_{\Phi,\prec}$ be the induced graph for a set of factors $\Phi$
and some elimination ordering $\prec$. Then

1. The scope of every factor generated during VE is a clique in
$\mathcal{I}_{\Phi,\prec}$.
2. Every maximal clique in $\mathcal{I}_{\Phi,\prec}$ is the scope of some
intermediate factor in the computation.
    - The set of maximal cliques in $\mathcal{I}_{\Phi,\prec}$ corresponds
    exactly to the set of intermediate factors ($\psi$s) generated during VE.
    - The size of the maximal cliques depends on $\prec$.
</thm>

</font>

## Complexity: tree-width

<font size="5">

<def>
The *width* of $\mathcal{I}_{\Phi,\prec}$ is the number of nodes in its largest
clique minus 1.
</def>

<def>
The *induced width*, $w_{\mathcal{K},\prec}$ of an ordering
$\prec$ relative to a graph $\mathcal{K}$ is the width of
$\mathcal{I}_{\mathcal{K},\prec}$ from applying VE to $\mathcal{K}$ using 
$\prec$.
</def>

<def>
The *tree-width* of graph $\mathcal{K}$ is its minimal induced width
$\mathcal{w}_\mathcal{K}^*=\min_\prec\mathcal{w}_{\mathcal{K},\prec}$.
</def>

The complexity of running VE on some $P_\Phi$ that factorizes over $\mathcal{K}$
is $O(mv^{\mathcal{w}_{\mathcal{K}}^*})$, where $m$ is the number of initial
factors ($\phi$s) and $v$ bounds the number of values per variable.

Unfortunately, finding $\underset{\prec}{\argmin} \ w_{\mathcal{H},\prec}$ is
$\mathcal{NP}$-hard.

</font>

## Elimination orderings

<font size="5">

<thm>
Every induced graph is chordal.
</thm>

</font>